app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - mysql
postgres:
  image: postgres:9.4
  ports:
    - "5432"

mysql:
  image: mysql:5.7
  volumes:
    - db_data:/var/lib/mysql
  ports:
    - "13306:3306"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: Phann123@123
    MYSQL_DATABASE: blog
    MYSQL_USER: root
    MYSQL_PASSWORD: Phann123@123    